# Generated by Django 2.2.7 on 2019-11-24 02:13

from django.db import migrations, models

import taggit.managers
import versatileimagefield.fields
from markdownfield.models import MarkdownField, RenderedMarkdownField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='100 characters or fewer.', max_length=100)),
                ('where', models.CharField(max_length=200)),
                ('what', MarkdownField()),
                ('what_rendered', RenderedMarkdownField(editable=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='events')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
