# Generated by Django 2.2.7 on 2019-11-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start']},
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
