# Generated by Django 2.2.8 on 2019-12-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End date and time are optional.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Time is optional.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(blank=True, help_text='End date and time are optional.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(),
        ),
    ]
