# Generated by Django 3.0 on 2019-12-19 23:49
from django.db import migrations

from markdownfield.models import MarkdownField


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_split_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='what',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='what_rendered',
            new_name='description_rendered',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='where',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=MarkdownField(rendered_field='description_rendered'),
        ),
    ]
