# Generated by Django 3.0 on 2019-12-23 00:58

from django.db import migrations
from django.utils.text import slugify

from slugger import AutoSlugField


def generate_slugs(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        event.slug = slugify(event.title)
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=AutoSlugField(null=True, populate_from='title', unique_for_year='start'),
        ),
        migrations.RunPython(generate_slugs),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=AutoSlugField(populate_from='title', unique_for_year='start'),
        ),
    ]
