# Generated by Django 2.2.7 on 2019-11-17 04:34

from django.db import migrations, models

import apps.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits, spaces, and @/./+/-/_ only.', max_length=30, unique=True, validators=[apps.accounts.validators.UsernameValidator()], verbose_name='username'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
    ]
