# Generated by Django 3.0 on 2019-12-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_username_spaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_URL',
        ),
    ]
