# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: 'node_modules|storage|build|.git|.pytest_cache|.tox'
default_language_version:
    python: python3.13
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-builtin-literals
    -   id: check-added-large-files
        args: ['--maxkb=1024']

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: b969e2851312ca2b24bbec879ba4954341d1bd12  # v0.15.5
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: biome-check
        name: biome check
        entry: npx biome check --no-errors-on-unmatched
        language: system
        files: '\.jsx?$'
    -   id: stylelint
        name: stylelint
        entry: npx stylelint
        language: system
        files: '\.scss$'
