services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: foxtail
      POSTGRES_PASSWORD: foxtail
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foxtail"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  foxtail:
    image: dmptrluke/foxtail:latest
    build:
      context: .
      target: dev
      args:
        BUILD_MODE: development
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://foxtail:foxtail@db/foxtail"
      CACHE_URL: "redis://redis/1"
      SERVICE_NAME: "app"
    volumes:
      - storage:/app/storage
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      worker:
        condition: service_started

  worker:
    image: dmptrluke/foxtail:latest
    environment:
      DATABASE_URL: "postgres://foxtail:foxtail@db/foxtail"
      CACHE_URL: "redis://redis/1"
      SERVICE_NAME: "worker"
    volumes:
      - storage:/app/storage
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: django-admin run_huey

volumes:
  storage:
  db:
  redis:
