---
version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: foxtail
      POSTGRES_PASSWORD: foxtail
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6
    environment:
      POSTGRES_USER: foxtail
      POSTGRES_PASSWORD: foxtail
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  foxtail:
    image: dmptrluke/foxtail:latest
    build:
      context: .
      args:
        BUILD_MODE: "development"
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DEBUG: "True"
      DATABASE_URL: "postgres://foxtail:foxtail@db/foxtail"
      CACHE_URL: "redis://redis/1"
    volumes:
      - storage:/app/storage

volumes:
  storage:
  db:
  redis:
