---
version: "3.8"

networks:
  primary:
    name: primary
    external: true

services:
  db:
    image: postgres:16
    networks:
      - primary
    environment:
      POSTGRES_USER: foxtail
      POSTGRES_PASSWORD: foxtail
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6
    networks:
      - primary
    environment:
      POSTGRES_USER: foxtail
      POSTGRES_PASSWORD: foxtail
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  foxtail:
    image: dmptrluke/foxtail:latest
    networks:
      - primary
    build:
      context: .
      args:
        BUILD_MODE: "development"
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE_URL: "postgres://foxtail:foxtail@db/foxtail"
      CACHE_URL: "redis://redis/1"
    volumes:
      - storage:/app/storage
    labels:
      - traefik.enable=true
      - traefik.http.routers.foxtail.rule=Host(`fnz.dmptr.com`)
      - traefik.http.routers.foxtail.tls=true
      - traefik.http.routers.foxtail.tls.certresolver=letsencrypt
      - traefik.http.routers.foxtail.middlewares=chain_standard@file
      - traefik.http.services.foxtail.loadbalancer.server.port=8000


volumes:
  storage:
  db:
  redis:
