# Generated by Django 5.2.12 on 2026-03-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='furry.nz', max_length=100)),
                ('org_description', models.TextField(blank=True, help_text='Short description for structured data and SEO.')),
                ('theme_color', models.CharField(default='#281e33', help_text='Hex color for browser theme-color meta tag.', max_length=7)),
                ('facebook_app_id', models.CharField(blank=True, max_length=50)),
                ('telegram_url', models.URLField(blank=True)),
                ('bluesky_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Public contact address shown on contact page.', max_length=254)),
            ],
            options={
                'verbose_name': 'site settings',
            },
        ),
    ]
