# Generated by Django 5.2.12 on 2026-03-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drop_sites_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'site settings', 'verbose_name_plural': 'site settings'},
        ),
    ]
