# Generated by Django 5.2.12 on 2026-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_verbose_name_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='bluesky_url',
            field=models.URLField(blank=True, verbose_name='Bluesky URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Public contact address shown on contact page.', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facebook App ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='org_description',
            field=models.TextField(blank=True, help_text='Short description for structured data and SEO.', verbose_name='Organisation Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='org_name',
            field=models.CharField(default='furry.nz', max_length=100, verbose_name='Organisation Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme_color',
            field=models.CharField(default='#281e33', help_text='Hex color for browser theme-color meta tag.', max_length=7, verbose_name='Theme Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='x_url',
            field=models.URLField(blank=True, verbose_name='X URL'),
        ),
    ]
