# Generated by Django 5.2.12 on 2026-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_field_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Content value from the Google Search Console meta tag.', max_length=100, verbose_name='Google Site Verification'),
        ),
    ]
