# Generated by Django 2.2.7 on 2019-11-18 05:13

from django.db import migrations, models

from markdownfield.fields import MarkdownField


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='body_rendered',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=MarkdownField(),
        ),
    ]
