# Generated by Django 2.2.7 on 2019-11-18 05:13

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='body_rendered',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=apps.core.fields.MarkdownField(),
        ),
    ]
