# Generated by Django 2.2.7 on 2019-11-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='Changing this value after initial creation will break existing page URLs. Must be unique.', unique=True),
        ),
    ]
