# Generated by Django 3.0.2 on 2020-01-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_markdownfield_squashed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
        migrations.RemoveField(
            model_name='page',
            name='show_in_menu',
        ),
        migrations.RemoveField(
            model_name='page',
            name='sort_order',
        ),
    ]
