# Generated by Django 2.2.7 on 2019-11-24 02:36

from django.db import migrations
import foxtail_blog.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_pre-render_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body_rendered',
            field=foxtail_blog.fields.RenderedMarkdownField(editable=False),
        ),
    ]
