version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node
        environment:
          DEBUG: true
          SECRET_KEY: fakekey
          RECAPTCHA_PRIVATE_KEY: fakekey
          RECAPTCHA_PUBLIC_KEY: fakekey
          SITE_URL: test
          DATABASE_URL: postgres://root@localhost:5432/test
      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: test
    steps:
    - checkout
    - restore_cache:
        keys:
        - pip-{{ checksum "requirements.txt" }}-{{ checksum "package.json" }}
    - run:
        command: |
          if true; then
            pip install --user -r requirements.txt
            pip install --user -r .circleci/requirements.txt
          else
            pip install -r requirements.txt
            pip install -r .circleci/requirements.txt
          fi
        name: Install Python Dependencies
    - run:
        command: npm install
        name: Install Node Dependencies
    - save_cache:
        key: pip-{{ checksum "requirements.txt" }}-{{ checksum "package.json" }}
        paths:
        - /home/circleci/.local/lib/
        - ./node_modules
    - run:
        name: Generate assets
        command: npm run-script build-dev
    - run:
        name: Running tests
        command: python manage.py test 2>&1 | tee -a results.txt
    - store_artifacts:
        path: results.txt
