version: 2.1
jobs:
  update_dependencies:
    docker:
      - image: circleci/python:3.7-node
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "package.json" }}
            - pip-
      - run:
          command: |
            pip install --user -r requirements.txt
            pip install --user -r .circleci/requirements.txt
          name: Install Python Dependencies
      - run:
          command: npm install
          name: Install Node Dependencies
      - save_cache:
          key: pip-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "package.json" }}
          paths:
            - /home/circleci/.local/lib/
            - ./node_modules
  run_tests:
    docker:
      - image: circleci/python:3.7-node
        environment:
          DEBUG: true
          SECRET_KEY: fakekey
          RECAPTCHA_PUBLIC_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
          RECAPTCHA_PRIVATE_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
          SITE_URL: test
          CACHE_ENABLED: true
          CACHE_URL: memcache://localhost:11211
          DATABASE_URL: postgres://root@localhost:5432/test
      - image: memcached:1.5
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: test
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "package.json" }}
      - run:
          name: Generate assets
          command: npm run-script build-dev
      - run:
          name: Running tests
          command: |
            mkdir test-reports
            python -m pytest --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  sentry:
    docker:
      - image: circleci/buildpack-deps
        environment:
          SENTRY_PROJECT: furrynz
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install sentry-CLI
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: Save current git hash to sentry-release-version.txt
          command: git rev-parse HEAD > sentry-release-version.txt
      - run:
          name: Create a new Sentry release
          command: |
            VERSION=$(git rev-parse HEAD)
            sentry-cli releases --org "${SENTRY_ORG}" new \
              --project "${SENTRY_PROJECT}" "${VERSION}"
      - run:
          name: Set commits of a Sentry release
          command: >
            VERSION=$(cat sentry-release-version.txt)

            sentry-cli releases --org "${SENTRY_ORG}" set-commits --auto
            "${VERSION}"

      - run:
          name: Finalize a Sentry release
          command: >
            VERSION=$(cat sentry-release-version.txt)

            sentry-cli releases --org "${SENTRY_ORG}" finalize
            "${VERSION}"
workflows:
  version: 2
  build-and-test:
    jobs:
      - update_dependencies
      - run_tests:
          requires:
            - update_dependencies
      - sentry:
          context: Sentry
          filters:
            branches:
              only: master
