# Generated by Django 3.0.2 on 2020-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_integer_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_age',
            field=models.BooleanField(default=False, verbose_name='Share my Age'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_birthday',
            field=models.BooleanField(default=False, verbose_name='Share my Birthday'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_name',
            field=models.BooleanField(default=False, verbose_name='Share my Full Name'),
        ),
    ]
