# Generated by Django 4.2.15 on 2024-09-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_dob_privacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'character', 'verbose_name_plural': 'characters'},
        ),
    ]
