# Generated by Django 5.2.12 on 2026-03-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_geocoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='events', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
    ]
