# Generated by Django 5.2.12 on 2026-03-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_image_remove_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='live_as_of',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='publish_status',
            field=models.SmallIntegerField(choices=[(0, 'Never Available'), (1, 'Available Now'), (2, 'Available after "Publish Date"')], default=1, verbose_name='Publish'),
        ),
    ]
