# Generated by Django 5.2.12 on 2026-03-10 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_add_published_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='map_image',
        ),
    ]
