# Generated by Django 5.2.12 on 2026-03-16 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventinterest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventinterest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='eventinterest',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='events_eventinterest_event_user_uniq'),
        ),
    ]
