# Generated by Django 5.2.12 on 2026-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_unique_together_use_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_requirement',
            field=models.CharField(blank=True, choices=[('all', 'All Ages'), ('13', '13+'), ('16', '16+'), ('18', '18+')], max_length=3),
        ),
    ]
