# Generated by Django 5.2.12 on 2026-04-04 08:53

import apps.images.upload
import apps.images.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial_squashed_0018_age_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to=apps.images.upload.scramble_upload('events'), validators=[apps.images.validators.FileSizeValidator()], width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publish_status',
            field=models.SmallIntegerField(choices=[(0, 'Never Available'), (1, 'Available'), (2, 'Available after "Publish Date"')], default=1, verbose_name='Publish'),
        ),
    ]
