# Generated by Django 5.2.14 on 2026-05-12 08:35

import decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_field_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicketTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.00'))],
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        choices=[('NZD', 'NZD'), ('AUD', 'AUD'), ('USD', 'USD')],
                        default='NZD',
                        max_length=3,
                    ),
                ),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ticket_tiers',
                        to='events.event',
                    ),
                ),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventtickettier',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='events_tickettier_price_gte_0'),
        ),
    ]
