# Generated by Django 3.0 on 2020-01-07 02:19

from django.db import migrations, models
from django.utils.text import slugify

import apps.directory.validators


def gen_url(apps, schema_editor):
    Profile = apps.get_model('directory', 'Profile')
    for row in Profile.objects.all():
        row.profile_URL = slugify(row.user.username)
        row.save(update_fields=['profile_URL'])


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0001_initial_squashed'),
    ]

    operations = [
        migrations.RunPython(gen_url, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='profile_URL',
            field=models.CharField(max_length=25, unique=True, validators=[apps.directory.validators.URLValidator(),
                                                                           apps.directory.validators.validate_blacklist]),
        ),
    ]
