# Generated by Django 3.0 on 2019-12-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_profile_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
