# Generated by Django 3.0.2 on 2020-01-20 09:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='privacy_rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
