# Generated by Django 3.0.2 on 2020-03-03 02:52

from django.db import migrations

import apps.directory.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_privacy',
            field=apps.directory.fields.PrivacyField(),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday_privacy',
            field=apps.directory.fields.PrivacyField(),
        ),
    ]
