# Generated by Django 3.0.2 on 2020-01-16 03:17

from django.db import migrations, models

import apps.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0008_remove_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits, spaces, and @/./+/-/_ only.', max_length=30, unique=True, validators=[apps.accounts.validators.UsernameValidator(), apps.accounts.validators.validate_blacklist], verbose_name='username'),
        ),
    ]
