# Generated by Django 5.2.12 on 2026-03-06 23:19

import django.core.validators
import imagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_migrate_client_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagefield.fields.ImageField(blank=True, upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_ppoi',
            field=imagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
