# Generated by Django 5.2.12 on 2026-03-07 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_avatar_user_avatar_ppoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmetadata',
            name='logo_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='clientmetadata',
            name='logo_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='clientmetadata',
            name='logo_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='clientmetadata',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', upload_to='oidc/clients/', width_field='logo_width'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field='avatar_height', upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], width_field='avatar_width'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
    ]
