# Generated by Django 5.2.12 on 2026-03-17 03:56

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_create_moderators_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field='avatar_height', upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.FileSizeValidator()], width_field='avatar_width'),
        ),
    ]
