# Generated by Django 5.2.12 on 2026-04-04 08:53

import apps.images.upload
import apps.images.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_uuid_and_legacy_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmetadata',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', upload_to=apps.images.upload.scramble_upload('oidc/clients'), width_field='logo_width'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field='avatar_height', upload_to=apps.images.upload.scramble_upload('avatars'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.images.validators.FileSizeValidator()], width_field='avatar_width'),
        ),
    ]
