# Generated by Django 2.2.7 on 2019-11-18 13:58

from django.db import migrations

import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('foxtail_blog', '0002_pre-render_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
