# Generated by Django 2.2.7 on 2019-11-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxtail_blog', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='280 characters or fewer.', max_length=280),
        ),
    ]
