# Generated by Django 2.2.9 on 2019-12-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxtail_blog', '0006_rendered_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='live_as_of',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_status',
            field=models.SmallIntegerField(choices=[(0, 'Never Available'), (1, 'Available Now'), (2, 'Available after "Publish Date"')], default=1, verbose_name='Publish'),
        ),
    ]
