# Generated by Django 3.0 on 2020-01-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foxtail_blog', '0007_django_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
