# Generated by Django 3.0.2 on 2020-01-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxtail_blog', '0008_fix_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='140 characters or fewer.', max_length=140),
        ),
    ]
