# Generated by Django 3.0.2 on 2020-01-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foxtail_blog', '0009_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created',
        ),
    ]
