# Generated by Django 5.2.12 on 2026-03-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxtail_blog', '0016_remove_author_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, height_field='avatar_height', upload_to='blog/authors', width_field='avatar_width'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
