# Generated by Django 5.2.12 on 2026-03-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_organisation_event_series_alter_event_image'),
        ('foxtail_blog', '0018_blog_editors_group'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_series',
            field=models.ManyToManyField(blank=True, to='organisations.eventseries'),
        ),
        migrations.AddField(
            model_name='post',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
        migrations.AddField(
            model_name='post',
            name='organisations',
            field=models.ManyToManyField(blank=True, to='organisations.organisation'),
        ),
    ]
