# Generated by Django 5.2.12 on 2026-04-04 08:53

import apps.images.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_event_series_post_events_post_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, height_field='avatar_height', upload_to=apps.images.upload.scramble_upload('blog/authors'), width_field='avatar_width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to=apps.images.upload.scramble_upload('blog'), width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_status',
            field=models.SmallIntegerField(choices=[(0, 'Never Available'), (1, 'Available'), (2, 'Available after "Publish Date"')], default=1, verbose_name='Publish'),
        ),
    ]
