# Generated by Django 5.2.12 on 2026-03-13 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord'), ('twitter', 'Twitter / X'), ('bluesky', 'Bluesky'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('mastodon', 'Mastodon'), ('website', 'Website')], max_length=20)),
                ('url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-is_primary', 'platform'],
            },
        ),
    ]
