# Generated by Django 5.2.12 on 2026-03-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
