# Generated by Django 5.2.12 on 2026-03-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
