# Generated by Django 5.2.12 on 2026-03-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisation_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name'], 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AddField(
            model_name='organisation',
            name='group_type',
            field=models.CharField(choices=[('organisation', 'Organisation'), ('community', 'Community Group'), ('interest', 'Interest Group')], default='organisation', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='region',
            field=models.CharField(blank=True, choices=[('auckland', 'Auckland'), ('waikato', 'Waikato'), ('bay-of-plenty', 'Bay of Plenty'), ('wellington', 'Wellington'), ('canterbury', 'Canterbury'), ('otago', 'Otago'), ('southland', 'Southland'), ('nationwide', 'Nationwide'), ('online', 'Online')], max_length=20),
        ),
    ]
