# Generated by Django 5.2.12 on 2026-03-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_organisation_country_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='region',
            field=models.CharField(blank=True, choices=[('northland', 'Northland'), ('auckland', 'Auckland'), ('waikato', 'Waikato'), ('bay-of-plenty', 'Bay of Plenty'), ('central-ni', 'Central North Island'), ('wellington', 'Wellington'), ('top-of-the-south', 'Top of the South'), ('canterbury', 'Canterbury'), ('otago', 'Otago'), ('southland', 'Southland'), ('nationwide', 'Nationwide'), ('online', 'Online')], max_length=20),
        ),
    ]
