# Generated by Django 5.2.12 on 2026-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisation_region_choices_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='age_requirement',
            field=models.CharField(blank=True, choices=[('all', 'All Ages'), ('13', '13+'), ('16', '16+'), ('18', '18+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='region',
            field=models.CharField(blank=True, choices=[('northland', 'Northland'), ('auckland', 'Auckland'), ('waikato', 'Waikato'), ('bay-of-plenty', 'Bay of Plenty'), ('central-ni', 'Central North Island'), ('wellington', 'Wellington'), ('top-of-the-south', 'Nelson/Marlborough'), ('canterbury', 'Canterbury'), ('otago', 'Otago'), ('southland', 'Southland'), ('nationwide', 'Nationwide'), ('online', 'Online')], max_length=20),
        ),
    ]
