# Generated by Django 5.2.12 on 2026-03-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_age_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
