# Generated by Django 5.2.12 on 2026-04-04 08:53

import apps.images.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial_squashed_0009_add_sociallink_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventseries',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', upload_to=apps.images.upload.scramble_upload('organisations/series'), width_field='logo_width'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', upload_to=apps.images.upload.scramble_upload('organisations'), width_field='logo_width'),
        ),
    ]
