# Generated by Django 5.2.12 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_field_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='region',
            field=models.CharField(
                blank=True,
                choices=[
                    ('northland', 'Northland'),
                    ('auckland', 'Auckland'),
                    ('waikato', 'Waikato'),
                    ('bay-of-plenty', 'Bay of Plenty'),
                    ('central-ni', 'Central North Island'),
                    ('manawatu-whanganui', 'Manawatū-Whanganui'),
                    ('wellington', 'Wellington'),
                    ('top-of-the-south', 'Nelson/Marlborough'),
                    ('canterbury', 'Canterbury'),
                    ('otago', 'Otago'),
                    ('southland', 'Southland'),
                    ('nationwide', 'Nationwide'),
                    ('online', 'Online'),
                ],
                max_length=20,
            ),
        ),
    ]
