# Generated by Django 5.2.12 on 2026-03-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, max_length=32)),
                ('token', models.CharField(max_length=86, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'link token',
                'indexes': [models.Index(fields=['telegram_id'], name='telegram_li_telegra_ce78b5_idx')],
            },
        ),
    ]
