# Generated by Django 5.2.12 on 2026-03-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_link_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotAction',
        ),
    ]
