# Generated by Django 5.2.12 on 2026-03-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_drop_botaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktoken',
            name='first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
