name: Cleanup Container Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  prune-branches:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: foxtail
          cut-off: 7d
          keep-n-most-recent: 10
          image-tags: "!latest !master !v*"

  prune-releases:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: foxtail
          cut-off: 180d
          keep-n-most-recent: 5
          image-tags: "v*"
