name: Inspect
on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Preform pre-commit analysis
      uses: pre-commit/action@v3.0.1
      